import type { Company } from './types';

// Curated and comprehensive as of early 2026. Structured as data so it stays
// easy to extend. Each entry links out so you can check the very latest.
export const companies: Company[] = [
  // ---------- Frontier labs ----------
  {
    id: 'openai', name: 'OpenAI', founded: '2015', founders: 'Sam Altman, Elon Musk, Ilya Sutskever, Greg Brockman & others', country: 'USA', type: 'Frontier Lab',
    what: 'Builds frontier general-purpose models; makers of ChatGPT.',
    flagship: ['GPT-series', 'o-series (reasoning)', 'ChatGPT', 'DALL·E', 'Sora', 'Whisper'],
    focus: 'Frontier reasoning models, agents, multimodal, and the ChatGPT product ecosystem.',
    notable: 'ChatGPT (Nov 2022) hit ~100M users in two months — the spark of the current AI boom. Closely partnered with Microsoft.',
    url: 'https://openai.com',
  },
  {
    id: 'anthropic', name: 'Anthropic', founded: '2021', founders: 'Dario & Daniela Amodei (ex-OpenAI) & team', country: 'USA', type: 'Frontier Lab',
    what: 'Safety-focused frontier lab; makers of Claude and creators of MCP.',
    flagship: ['Claude (Opus / Sonnet / Haiku)', 'Claude Code', 'Model Context Protocol (MCP)'],
    focus: 'Frontier Claude models, coding & agents, interpretability, and AI safety ("Constitutional AI").',
    notable: 'Introduced MCP (2024), now an industry-wide standard for connecting models to tools. Backed by Amazon and Google.',
    url: 'https://anthropic.com',
  },
  {
    id: 'google-deepmind', name: 'Google DeepMind', founded: '2010 (DeepMind) / merged 2023', founders: 'Demis Hassabis, Shane Legg, Mustafa Suleyman', country: 'UK / USA', type: 'Frontier Lab',
    what: 'Google’s unified AI lab; makers of Gemini and landmark research systems.',
    flagship: ['Gemini', 'Gemma (open)', 'AlphaFold', 'AlphaGo', 'Veo', 'Imagen'],
    focus: 'Gemini frontier & on-device models, agents, and AI-for-science.',
    notable: 'AlphaGo beat a Go world champion (2016); AlphaFold’s protein-structure work earned a 2024 Nobel Prize in Chemistry.',
    url: 'https://deepmind.google',
  },
  {
    id: 'meta-ai', name: 'Meta AI (FAIR)', founded: '2013 (FAIR)', founders: 'Part of Meta; research led by Yann LeCun & others', country: 'USA', type: 'Frontier Lab',
    what: 'Meta’s AI research; champion of open-weight models.',
    flagship: ['Llama family (open weights)', 'Segment Anything', 'PyTorch (origin)'],
    focus: 'Open foundation models, assistants across Meta apps, and AI research.',
    notable: 'The open-weight Llama models kicked off the local/open-source LLM movement. Meta also created PyTorch.',
    url: 'https://ai.meta.com',
  },
  {
    id: 'mistral', name: 'Mistral AI', founded: '2023', founders: 'Arthur Mensch, Guillaume Lample, Timothée Lacroix', country: 'France', type: 'Frontier Lab',
    what: 'European frontier lab known for efficient open and commercial models.',
    flagship: ['Mistral / Mixtral (open)', 'Le Chat assistant', 'Codestral'],
    focus: 'Efficient open-weight and commercial models; Europe’s flagship AI champion.',
    notable: 'Popularized the "Mixture-of-Experts" (MoE) approach in accessible open models.',
    url: 'https://mistral.ai',
  },
  {
    id: 'xai', name: 'xAI', founded: '2023', founders: 'Elon Musk & team', country: 'USA', type: 'Frontier Lab',
    what: 'Elon Musk’s AI lab; makers of Grok, integrated with X (Twitter).',
    flagship: ['Grok'],
    focus: 'Frontier models with real-time access to X data; very large training clusters ("Colossus").',
    notable: 'Built one of the world’s largest GPU training clusters at remarkable speed.',
    url: 'https://x.ai',
  },
  {
    id: 'deepseek', name: 'DeepSeek', founded: '2023', founders: 'Liang Wenfeng (High-Flyer)', country: 'China', type: 'Frontier Lab',
    what: 'Chinese lab famous for strong, cheap, open-weight models.',
    flagship: ['DeepSeek-V3', 'DeepSeek-R1 (reasoning, open)'],
    focus: 'Highly efficient open models, especially reasoning, at low training cost.',
    notable: 'DeepSeek-R1 (early 2025) showed frontier-level reasoning could be trained far more cheaply — and open — shaking the market.',
    url: 'https://deepseek.com',
  },
  {
    id: 'alibaba-qwen', name: 'Alibaba (Qwen)', founded: '1999 (Alibaba)', founders: 'Jack Ma & others', country: 'China', type: 'Frontier Lab',
    what: 'Alibaba’s Qwen team ships a large, popular family of open models.',
    flagship: ['Qwen (open, many sizes & modalities)'],
    focus: 'Broad open-weight model family widely used and fine-tuned by the community.',
    notable: 'Qwen is among the most-downloaded open model families on Hugging Face.',
    url: 'https://qwenlm.github.io',
  },
  {
    id: 'cohere', name: 'Cohere', founded: '2019', founders: 'Aidan Gomez (Transformer co-author), Nick Frosst, Ivan Zhang', country: 'Canada', type: 'Frontier Lab',
    what: 'Enterprise-focused LLMs and best-in-class embeddings/RAG tooling.',
    flagship: ['Command models', 'Embed / Rerank'],
    focus: 'Secure, enterprise & on-prem generative AI and retrieval.',
    notable: 'Co-founder Aidan Gomez was a co-author of the original Transformer paper.',
    url: 'https://cohere.com',
  },
  {
    id: 'ai21', name: 'AI21 Labs', founded: '2017', founders: 'Yoav Shoham, Ori Goshen, Amnon Shashua', country: 'Israel', type: 'Frontier Lab',
    what: 'Builds LLMs (Jamba family) and enterprise language tools.',
    flagship: ['Jamba (hybrid SSM-Transformer)'],
    focus: 'Efficient long-context enterprise models.',
    notable: 'Pioneered hybrid architectures mixing Transformers with state-space models.',
    url: 'https://www.ai21.com',
  },

  // ---------- Big tech ----------
  {
    id: 'microsoft', name: 'Microsoft', founded: '1975', founders: 'Bill Gates, Paul Allen', country: 'USA', type: 'Big Tech',
    what: 'Major OpenAI partner; ships Copilot across its products and Azure.',
    flagship: ['Copilot', 'Azure OpenAI / Azure AI', 'Phi (small open models)'],
    focus: 'Embedding AI "Copilots" into Windows, Office, GitHub; cloud AI on Azure.',
    notable: 'Multi-billion-dollar investment in and partnership with OpenAI; GitHub Copilot popularized AI pair-programming.',
    url: 'https://microsoft.com/ai',
  },
  {
    id: 'google', name: 'Google', founded: '1998', founders: 'Larry Page, Sergey Brin', country: 'USA', type: 'Big Tech',
    what: 'Ships Gemini across Search, Workspace, Android, and Google Cloud.',
    flagship: ['Gemini app', 'AI Overviews in Search', 'Vertex AI', 'NotebookLM'],
    focus: 'AI across all products; designs its own TPU chips.',
    notable: 'Invented the Transformer (2017) and runs AI on custom TPUs.',
    url: 'https://ai.google',
  },
  {
    id: 'amazon', name: 'Amazon / AWS', founded: '1994', founders: 'Jeff Bezos', country: 'USA', type: 'Big Tech',
    what: 'Cloud leader; offers many models via Bedrock and its own Nova models.',
    flagship: ['Amazon Bedrock', 'Nova models', 'Trainium / Inferentia chips', 'Alexa+'],
    focus: 'Multi-model cloud platform, custom AI chips, and a major Anthropic investment.',
    notable: 'Bedrock lets you call Claude, Llama, Mistral and more behind one API.',
    url: 'https://aws.amazon.com/ai/',
  },
  {
    id: 'apple', name: 'Apple', founded: '1976', founders: 'Steve Jobs, Steve Wozniak, Ronald Wayne', country: 'USA', type: 'Big Tech',
    what: 'Privacy-first, on-device AI woven into iPhone/Mac ("Apple Intelligence").',
    flagship: ['Apple Intelligence', 'On-device foundation models', 'Private Cloud Compute'],
    focus: 'Small efficient on-device models; partners for larger cloud queries.',
    notable: 'Bets on running AI locally on the device for privacy.',
    url: 'https://www.apple.com/apple-intelligence/',
  },
  {
    id: 'nvidia', name: 'NVIDIA', founded: '1993', founders: 'Jensen Huang, Chris Malachowsky, Curtis Priem', country: 'USA', type: 'Hardware',
    what: 'Makes the GPUs nearly all AI is trained and run on; CUDA software moat.',
    flagship: ['H100 / H200 / Blackwell GPUs', 'CUDA', 'NeMo'],
    focus: 'AI accelerators, networking, and full-stack AI infrastructure.',
    notable: 'Became one of the most valuable companies on Earth as the "picks-and-shovels" supplier of the AI boom.',
    url: 'https://www.nvidia.com/en-us/ai/',
  },
  {
    id: 'baidu', name: 'Baidu', founded: '2000', founders: 'Robin Li, Eric Xu', country: 'China', type: 'Big Tech',
    what: 'Chinese search giant; makers of the Ernie (文心) models.',
    flagship: ['Ernie Bot / Ernie models'],
    focus: 'Chinese-market foundation models and AI cloud.',
    notable: 'One of the first big Chinese ChatGPT competitors.',
    url: 'https://www.baidu.com',
  },

  // ---------- Platforms / tools ----------
  {
    id: 'huggingface', name: 'Hugging Face', founded: '2016', founders: 'Clément Delangue, Julien Chaumond, Thomas Wolf', country: 'France / USA', type: 'Platform / Tools',
    what: 'The "GitHub of AI": hub for open models, datasets, and demos.',
    flagship: ['Model Hub', 'Transformers library', 'Datasets', 'Spaces'],
    focus: 'Open-source AI ecosystem and free learning courses.',
    notable: 'Hosts hundreds of thousands of open models; the default home of open AI.',
    url: 'https://huggingface.co',
  },
  {
    id: 'perplexity', name: 'Perplexity', founded: '2022', founders: 'Aravind Srinivas & team', country: 'USA', type: 'Platform / Tools',
    what: 'An "answer engine" — AI search that cites its sources.',
    flagship: ['Perplexity answer engine', 'Comet browser'],
    focus: 'AI-native search and research with citations.',
    notable: 'Popularized chat-style search that links to real sources.',
    url: 'https://perplexity.ai',
  },
  {
    id: 'anysphere', name: 'Anysphere (Cursor)', founded: '2022', founders: 'Michael Truell & team', country: 'USA', type: 'Platform / Tools',
    what: 'Makers of Cursor, a leading AI-powered code editor.',
    flagship: ['Cursor'],
    focus: 'AI-first IDE for fast, agentic coding.',
    notable: 'One of the fastest-growing developer tools of the AI era.',
    url: 'https://cursor.com',
  },
  {
    id: 'github', name: 'GitHub (Copilot)', founded: '2008 (Microsoft-owned)', founders: 'Tom Preston-Werner & others', country: 'USA', type: 'Platform / Tools',
    what: 'Makers of GitHub Copilot, the mainstream AI coding assistant.',
    flagship: ['GitHub Copilot'],
    focus: 'AI pair-programming in editors, plus coding agents.',
    notable: 'Brought AI coding to millions of developers first, in 2021–22.',
    url: 'https://github.com/features/copilot',
  },
  {
    id: 'langchain', name: 'LangChain', founded: '2022', founders: 'Harrison Chase', country: 'USA', type: 'Platform / Tools',
    what: 'Popular framework for building LLM apps and agents; makers of LangGraph.',
    flagship: ['LangChain', 'LangGraph', 'LangSmith (observability)'],
    focus: 'Agent orchestration, tooling, and production observability.',
    notable: 'Among the most-used open-source LLM frameworks.',
    url: 'https://www.langchain.com',
  },
  {
    id: 'llamaindex', name: 'LlamaIndex', founded: '2022', founders: 'Jerry Liu', country: 'USA', type: 'Platform / Tools',
    what: 'Data framework for connecting your documents to LLMs (RAG).',
    flagship: ['LlamaIndex', 'LlamaParse', 'LlamaCloud'],
    focus: 'Indexing, retrieval, and document-centric agents.',
    notable: 'A go-to library for "chat with your data" applications.',
    url: 'https://www.llamaindex.ai',
  },
  {
    id: 'ollama', name: 'Ollama', founded: '2023', founders: 'Michael Chiang, Jeffrey Morgan', country: 'USA', type: 'Open Source',
    what: 'The easiest way to download and run open LLMs locally/offline.',
    flagship: ['Ollama'],
    focus: 'One-command local model running across Mac/Windows/Linux.',
    notable: '`ollama run llama3` gives you a private, offline chatbot in seconds.',
    url: 'https://ollama.com',
  },
  {
    id: 'pinecone', name: 'Pinecone', founded: '2019', founders: 'Edo Liberty', country: 'USA', type: 'Infra / Cloud',
    what: 'Managed vector database for embeddings and RAG.',
    flagship: ['Pinecone vector DB'],
    focus: 'Scalable semantic search and retrieval infrastructure.',
    notable: 'A popular hosted choice for production RAG.',
    url: 'https://www.pinecone.io',
  },
  {
    id: 'together', name: 'Together AI', founded: '2022', founders: 'Vipul Ved Prakash & others', country: 'USA', type: 'Infra / Cloud',
    what: 'Cloud for running and fine-tuning open models cheaply via one API.',
    flagship: ['Together inference & fine-tuning'],
    focus: 'Fast, affordable open-model inference and training.',
    notable: 'A favorite for serving Llama/Mistral/Qwen at scale.',
    url: 'https://www.together.ai',
  },

  // ---------- Media generation specialists ----------
  {
    id: 'midjourney', name: 'Midjourney', founded: '2021', founders: 'David Holz', country: 'USA', type: 'Startup',
    what: 'Beloved text-to-image generator known for striking aesthetics.',
    flagship: ['Midjourney image models'],
    focus: 'High-quality image (and increasingly video) generation.',
    notable: 'Famous for its art style; ran for years via a Discord bot.',
    url: 'https://www.midjourney.com',
  },
  {
    id: 'blackforest', name: 'Black Forest Labs', founded: '2024', founders: 'Robin Rombach & Stable Diffusion creators', country: 'Germany', type: 'Startup',
    what: 'Makers of the FLUX image models (open and pro).',
    flagship: ['FLUX'],
    focus: 'State-of-the-art open and commercial image generation.',
    notable: 'Founded by the original creators of Stable Diffusion.',
    url: 'https://blackforestlabs.ai',
  },
  {
    id: 'stability', name: 'Stability AI', founded: '2019', founders: 'Emad Mostaque & others', country: 'UK', type: 'Open Source',
    what: 'Released Stable Diffusion, which democratized open image generation.',
    flagship: ['Stable Diffusion', 'Stable Audio'],
    focus: 'Open generative models across image, audio, and video.',
    notable: 'Stable Diffusion (2022) made open, local image generation mainstream.',
    url: 'https://stability.ai',
  },
  {
    id: 'runway', name: 'Runway', founded: '2018', founders: 'Cristóbal Valenzuela & others', country: 'USA', type: 'Startup',
    what: 'Pioneer of AI video generation and creative tools.',
    flagship: ['Gen-series video models'],
    focus: 'Generative video for filmmakers and creators.',
    notable: 'Co-developed the original Stable Diffusion research.',
    url: 'https://runwayml.com',
  },
  {
    id: 'elevenlabs', name: 'ElevenLabs', founded: '2022', founders: 'Piotr Dąbkowski, Mati Staniszewski', country: 'UK / Poland', type: 'Startup',
    what: 'Leading AI voice synthesis and voice cloning.',
    flagship: ['Text-to-speech', 'Voice cloning', 'Dubbing'],
    focus: 'Ultra-realistic, multilingual AI voices.',
    notable: 'Set the bar for natural AI speech and dubbing.',
    url: 'https://elevenlabs.io',
  },
  {
    id: 'suno', name: 'Suno', founded: '2023', founders: 'Mikey Shulman & team', country: 'USA', type: 'Startup',
    what: 'Generates full songs (vocals + music) from a text prompt.',
    flagship: ['Suno music models'],
    focus: 'Consumer AI music creation.',
    notable: 'Made "type a prompt, get a song" mainstream.',
    url: 'https://suno.com',
  },

  // ---------- Hardware challengers ----------
  {
    id: 'groq', name: 'Groq', founded: '2016', founders: 'Jonathan Ross (ex-Google TPU)', country: 'USA', type: 'Hardware',
    what: 'Builds LPUs delivering extremely fast LLM inference.',
    flagship: ['LPU inference chips', 'GroqCloud'],
    focus: 'Record-low-latency token generation.',
    notable: 'Known for jaw-droppingly fast streaming responses.',
    url: 'https://groq.com',
  },
  {
    id: 'cerebras', name: 'Cerebras', founded: '2015', founders: 'Andrew Feldman & team', country: 'USA', type: 'Hardware',
    what: 'Makes the wafer-scale engine — the largest chip ever built.',
    flagship: ['Wafer-Scale Engine (WSE)'],
    focus: 'Giant single-chip systems for fast training and inference.',
    notable: 'Its chip is roughly the size of a dinner plate.',
    url: 'https://www.cerebras.ai',
  },
  {
    id: 'amd', name: 'AMD', founded: '1969', founders: 'Jerry Sanders & others', country: 'USA', type: 'Hardware',
    what: 'NVIDIA’s main GPU rival; Instinct accelerators + ROCm software.',
    flagship: ['Instinct MI-series GPUs', 'ROCm'],
    focus: 'Competitive AI training/inference accelerators.',
    notable: 'The leading open alternative to NVIDIA’s CUDA ecosystem.',
    url: 'https://www.amd.com/en/solutions/ai.html',
  },
];
