import type { GlossaryEntry } from '@/content/types';

// A searchable master list of the terms used across the course + atlas.
export const glossary: GlossaryEntry[] = [
  { term: 'Artificial Intelligence (AI)', short: 'Machines doing tasks that normally need human intelligence — the broadest umbrella.', category: 'Foundations' },
  { term: 'Machine Learning (ML)', short: 'Learning patterns from data instead of hand-coded rules; today’s dominant approach to AI.', category: 'Foundations' },
  { term: 'Deep Learning', short: 'ML using large multi-layer neural networks. Powers modern vision, speech, and language.', category: 'Foundations' },
  { term: 'Generative AI', short: 'Deep learning that creates new content: text, images, audio, video.', category: 'Foundations' },
  { term: 'Model', short: 'The trained bundle of numbers that maps an input to an output.', category: 'Foundations' },
  { term: 'Parameters', short: 'The adjustable numbers inside a model (e.g., 70B = 70 billion).', category: 'Foundations' },
  { term: 'Training', short: 'Adjusting a model’s parameters by showing it data.', category: 'Foundations' },
  { term: 'Inference', short: 'Using a trained model to produce an output.', category: 'Foundations' },
  { term: 'Supervised learning', short: 'Learning from labeled examples (input + correct answer).', category: 'Machine Learning' },
  { term: 'Unsupervised learning', short: 'Finding structure/groups in unlabeled data.', category: 'Machine Learning' },
  { term: 'Reinforcement learning', short: 'Learning by trial and error via rewards and penalties.', category: 'Machine Learning' },
  { term: 'Features', short: 'The input attributes given to a model.', category: 'Machine Learning' },
  { term: 'Label', short: 'The correct answer attached to a training example.', category: 'Machine Learning' },
  { term: 'Loss', short: 'A measure of how wrong the model’s predictions are.', category: 'Machine Learning' },
  { term: 'Gradient descent', short: 'The optimization method that reduces loss by following the slope downhill.', category: 'Machine Learning' },
  { term: 'Learning rate', short: 'How big each gradient-descent step is.', category: 'Machine Learning' },
  { term: 'Overfitting', short: 'Memorizing training data and failing to generalize to new data.', category: 'Machine Learning' },
  { term: 'Underfitting', short: 'Model too simple to capture the pattern.', category: 'Machine Learning' },
  { term: 'Precision / Recall / F1', short: 'Metrics for classifier quality: false-alarm rate, miss rate, and their balance.', category: 'Machine Learning' },
  { term: 'Neuron', short: 'Basic unit: weighted sum of inputs + bias, through an activation.', category: 'Neural Networks' },
  { term: 'Weight / Bias', short: 'The learned numbers a neuron uses to combine inputs.', category: 'Neural Networks' },
  { term: 'Activation function', short: 'Non-linear squash (ReLU, sigmoid, tanh) enabling complex learning.', category: 'Neural Networks' },
  { term: 'Backpropagation', short: 'Algorithm that assigns error blame to weights and updates them.', category: 'Neural Networks' },
  { term: 'CNN', short: 'Convolutional Neural Network — excels at images.', category: 'Neural Networks' },
  { term: 'RNN / LSTM', short: 'Older sequence models, largely replaced by Transformers.', category: 'Neural Networks' },
  { term: 'GPU / TPU', short: 'Chips that do massive parallel math, making training feasible.', category: 'Neural Networks' },
  { term: 'Transformer', short: 'The 2017 architecture behind virtually all modern LLMs.', category: 'LLMs' },
  { term: 'Self-attention', short: 'Lets each token weigh the relevance of every other token.', category: 'LLMs' },
  { term: 'LLM', short: 'Large Language Model — a big Transformer that predicts the next token.', category: 'LLMs' },
  { term: 'Token', short: 'A chunk of text (≈4 characters) that the model actually processes.', category: 'LLMs' },
  { term: 'Context window', short: 'Max tokens a model can consider at once — its short-term memory.', category: 'LLMs' },
  { term: 'Pretraining', short: 'Initial large-scale training to predict the next token.', category: 'LLMs' },
  { term: 'Fine-tuning', short: 'Extra training on curated data to specialize behavior.', category: 'LLMs' },
  { term: 'RLHF', short: 'Reinforcement Learning from Human Feedback — aligns models to be helpful/harmless.', category: 'LLMs' },
  { term: 'Temperature', short: 'Controls randomness/creativity of outputs.', category: 'LLMs' },
  { term: 'Hallucination', short: 'Confident but false model output.', category: 'LLMs' },
  { term: 'Multimodal', short: 'A model handling more than text (images, audio, video).', category: 'LLMs' },
  { term: 'Embedding', short: 'A vector representing meaning; similar things sit close together.', category: 'Prompting & RAG' },
  { term: 'Vector database', short: 'Store optimized for nearest-neighbor search over embeddings.', category: 'Prompting & RAG' },
  { term: 'Semantic search', short: 'Searching by meaning rather than exact keywords.', category: 'Prompting & RAG' },
  { term: 'Prompt', short: 'The text you send a model.', category: 'Prompting & RAG' },
  { term: 'System prompt', short: 'Persistent instructions defining the assistant’s role/rules.', category: 'Prompting & RAG' },
  { term: 'Few-shot', short: 'Including examples in the prompt to guide output.', category: 'Prompting & RAG' },
  { term: 'Chain-of-thought', short: 'Prompting the model to reason step by step.', category: 'Prompting & RAG' },
  { term: 'RAG', short: 'Retrieval-Augmented Generation: fetch relevant facts into the prompt before answering.', category: 'Prompting & RAG' },
  { term: 'Agent', short: 'An LLM that plans and uses tools in a loop to reach a goal.', category: 'Agents' },
  { term: 'Tool / Function calling', short: 'Letting a model invoke external functions and use the results.', category: 'Agents' },
  { term: 'ReAct', short: 'Pattern alternating Reasoning and Acting (tool calls).', category: 'Agents' },
  { term: 'Multi-agent system', short: 'Several specialized agents cooperating.', category: 'Agents' },
  { term: 'LangChain', short: 'Popular toolkit for chaining LLM calls, tools, and data.', category: 'Agents' },
  { term: 'LangGraph', short: 'Agent framework modeling workflows as graphs/state machines.', category: 'Agents' },
  { term: 'LlamaIndex', short: 'Framework focused on connecting your data to LLMs (RAG).', category: 'Agents' },
  { term: 'CrewAI / AutoGen', short: 'Frameworks for orchestrating multiple cooperating agents.', category: 'Agents' },
  { term: 'MCP', short: 'Model Context Protocol — open standard (Anthropic, 2024) to connect AI apps to tools/data.', category: 'Agents' },
  { term: 'Open-weight model', short: 'A model whose weights you can download and run yourself.', category: 'Industry' },
  { term: 'Closed / API model', short: 'A model used over the internet without access to its weights.', category: 'Industry' },
  { term: 'Quantization', short: 'Shrinking a model (lower-precision numbers) so it runs on smaller hardware.', category: 'On-device' },
  { term: 'GGUF', short: 'A popular file format for running quantized local models.', category: 'On-device' },
  { term: 'Alignment', short: 'Making a model’s behavior match human intent and values.', category: 'Safety' },
  { term: 'Constitutional AI', short: 'Anthropic’s approach: a model critiques itself against written principles.', category: 'Safety' },
  { term: 'Red-teaming', short: 'Attacking a model to find failures before release.', category: 'Safety' },
  { term: 'AGI / ASI', short: 'Artificial General / Super Intelligence — human-level / beyond-human breadth (timing debated).', category: 'Safety' },
];
