// Generates DEPENDENCIES.md from package.json + the actually-installed versions
// in node_modules. Run with:  npm run deps:doc
// (package.json + package-lock.json remain the source of truth; this is a
//  friendly, human-readable snapshot to keep updated as the project grows.)
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

// One-line purpose for each package (fallback: the package's own description).
const purpose = {
  react: 'UI library (components, hooks)',
  'react-dom': 'React renderer for the browser',
  'react-router-dom': 'Client-side routing (HashRouter, routes)',
  'framer-motion': 'Animations & transitions',
  'lucide-react': 'Icon set',
  '@fontsource-variable/inter': 'Self-hosted Inter font (offline, no CDN)',
  codemirror: 'In-browser code editor (DSA Java playground)',
  '@codemirror/lang-java': 'Java syntax highlighting for the editor',
  '@codemirror/state': 'CodeMirror editor state',
  '@codemirror/view': 'CodeMirror editor view/DOM',
  '@codemirror/theme-one-dark': 'Dark theme for the editor',
  vite: 'Build tool & dev server',
  '@vitejs/plugin-react': 'React Fast Refresh + JSX for Vite',
  typescript: 'Type checking (tsc --noEmit)',
  tailwindcss: 'Utility-first CSS framework',
  postcss: 'CSS processing pipeline (for Tailwind)',
  autoprefixer: 'Adds vendor prefixes to CSS',
  '@types/node': 'TypeScript types for Node APIs',
  '@types/react': 'TypeScript types for React',
  '@types/react-dom': 'TypeScript types for React DOM',
};

function installedVersion(name) {
  try {
    return JSON.parse(readFileSync(join(root, 'node_modules', name, 'package.json'), 'utf8')).version;
  } catch {
    return '(not installed)';
  }
}

function describe(name) {
  if (purpose[name]) return purpose[name];
  try {
    return JSON.parse(readFileSync(join(root, 'node_modules', name, 'package.json'), 'utf8')).description || '';
  } catch {
    return '';
  }
}

function table(deps) {
  const rows = Object.entries(deps)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, range]) => `| \`${name}\` | ${installedVersion(name)} | ${range} | ${describe(name)} |`);
  return ['| Package | Installed | Declared | Purpose |', '|---|---|---|---|', ...rows].join('\n');
}

const md = `# Dependencies

> Auto-generated by \`npm run deps:doc\` (from \`package.json\` + installed \`node_modules\`).
> The source of truth is **package.json** (declared ranges) and **package-lock.json** (exact locked versions).
> Last generated: ${new Date().toISOString().slice(0, 10)}

**Tooling:** Node.js ${process.version} · npm (see package-lock). All packages install into the project-local \`node_modules/\` — nothing global.

## Runtime dependencies
${table(pkg.dependencies || {})}

## Dev dependencies
${table(pkg.devDependencies || {})}

## Runtime externals (not npm packages)

| Name | Version | Purpose |
|---|---|---|
| CheerpJ (WASM JVM) | 3.0 (loaded from \`cjrtnc.leaningtech.com\` CDN) | Compiles & runs Java in the browser for the DSA playground. Configured in \`src/features/dsa/runner/cheerpj.ts\`. Needs internet only when you click "Run". |
| \`tools.jar\` (Java 8) | bundled in \`public/tools.jar\` | The \`javac\` compiler CheerpJ uses. Served locally at \`/app/tools.jar\`. |

## How to keep this updated
After adding/removing/upgrading any package, run:

\`\`\`bash
npm run deps:doc
\`\`\`
`;

writeFileSync(join(root, 'DEPENDENCIES.md'), md);
console.log('[gen-deps] wrote DEPENDENCIES.md');
